# Azure Cloud Configuration

# Azure Container Instances Configuration
azure:
  # Resource Group
  resource_group: "bus-simulation-rg"
  location: "East US"
  
  # Container Configuration
  container:
    name: "bus-simulation-container"
    image: "bus-simulation:latest"
    cpu_cores: 2.0
    memory_gb: 4.0
    restart_policy: "Never"  # For batch jobs
    
  # Storage Configuration
  storage:
    account_name: "bussimulationstorage"
    container_name: "simulation-data"
    # Mount paths
    input_mount: "/app/input"
    output_mount: "/app/output"
    
  # Batch Service Configuration (Alternative to ACI)
  batch:
    account_name: "bussimulationbatch"
    pool_name: "simulation-pool"
    pool_vm_size: "Standard_D2s_v3"
    pool_vm_count: 2
    job_timeout_minutes: 1440  # 24 hours
    
  # Monitoring & Logging
  monitoring:
    log_analytics_workspace: "bus-simulation-logs"
    application_insights: "bus-simulation-insights"
    
  # Networking (if needed)
  networking:
    vnet_name: "bus-simulation-vnet"
    subnet_name: "container-subnet"

# Environment-specific settings
environment:
  production:
    cpu_cores: 4.0
    memory_gb: 8.0
    timeout_hours: 48
    
  development:
    cpu_cores: 1.0
    memory_gb: 2.0
    timeout_hours: 4
    
  testing:
    cpu_cores: 0.5
    memory_gb: 1.0
    timeout_hours: 1 