# Bus Transit Simulation Configuration

# Simulation Parameters
simulation:
  # Time period for simulation
  start_date: "2024-01-01"  # YYYY-MM-DD format
  end_date: "2024-01-07"    # 7 days by default
  time_step: 5              # minutes
  
  # Fleet Configuration
  buses_per_line: 6
  
  # Randomization Settings
  randomize_travel_times: true
  randomize_passenger_demand: true
  weather_effects_probability: 0.15
  seed: 42

# Data Sources
data:
  stops_file: "data/ankara_bus_stops.csv"
  
# Output Settings  
output:
  directory: "output"
  summary: true
  debug: false

# Performance Settings
performance:
  max_memory_gb: 4
  max_cpu_cores: 2
  timeout_hours: 24 